http:
  serversTransports:
    adguardhome-doh-transport:
      insecureSkipVerify: true
  middlewares:
    test-ipwhitelist:
      ipWhiteList:
        sourceRange:
          - "222.67.5.147/32"
    basic-auth:
      basicAuth:
        usersFile: "/etc/traefik/secrets/credentials"
