accessLog: {}

log:
  level: INFO

api:
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"

  websecure:
    address: ":443"

certificatesResolvers:
  cloudflareresolver:
    acme:
      storage: /etc/traefik/secrets/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0

providers:
  file:
    directory: /etc/traefik
    watch: true
  docker:
    exposedByDefault: false

tls:
  options:
    default:
      minVersion: VersionTLS13
